### ISSUE TITLE
how to use cores in jupyter notebook

### ISSUE THREAD

**Issue by MCdeineMudda** [wbrueckner/cv2PYNQ-The-project-behind-the-library#3]
Hi,
i am pretty new to this topic, but want to get involved.

in your example notebook you used sobel like this 
"cv2.Sobel(inframe,-1,1,0,ksize=5,dst=outframe)"

how do i use the other filters, or where do i see which attributes they need? 
thanks in advance

**Comment by wbrueckner** [comment]
Hi,
most of the filters are within the "Image Filtering" module of OpenCV.
The documentation also includes the Python calls and its parameters.
https://docs.opencv.org/3.4.3/d4/d86/group__imgproc__filter.html
